#!/usr/bin/env bash

# Enable Memory + Bus Master (for DMA use cases): DOM FPGA 1
old=$(sudo setpci -s 05:00.0 0x04.W); \
new=$(printf "%04x" $((0x$old | 0x0006))); \
sudo setpci -s 05:00.0 0x04.W=$new

# Enable Memory + Bus Master (for DMA use cases): DOM FPGA 2
old=$(sudo setpci -s 08:00.0 0x04.W); \
new=$(printf "%04x" $((0x$old | 0x0006))); \
sudo setpci -s 08:00.0 0x04.W=$new
