# Accton Platform modules

FACEBOOK_WEDGE400_PLATFORM_MODULE_VERSION = 1.1

export FACEBOOK_WEDGE400_PLATFORM_MODULE_VERSION


FACEBOOK_WEDGE400_PLATFORM_MODULE = sonic-platform-facebook-wedge400_$(FACEBOOK_WEDGE400_PLATFORM_MODULE_VERSION)_amd64.deb
$(FACEBOOK_WEDGE400_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-facebook
$(FACEBOOK_WEDGE400_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON) $(PDDF_PLATFORM_MODULE_SYM)
$(FACEBOOK_WEDGE400_PLATFORM_MODULE)_PLATFORM = x86_64-facebook_wedge400-r0
SONIC_DPKG_DEBS += $(FACEBOOK_WEDGE400_PLATFORM_MODULE)

$(eval $(call add_extra_package,$(FACEBOOK_WEDGE400_PLATFORM_MODULE),$(FACEBOOK_WEDGE400_PLATFORM_MODULE)))
